//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public int assignmentID { get; set; }
        public string assignmentName { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> courseID { get; set; }
    
        public virtual cours cours { get; set; }
    }
}
