//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class grade
    {
        public int index { get; set; }
        public Nullable<int> studentID { get; set; }
        public Nullable<int> assignmentID { get; set; }
        public Nullable<int> grade1 { get; set; }
        public byte[] submittedAssignment { get; set; }
        [JsonIgnore]
        public virtual assignment assignment { get; set; }
        [JsonIgnore]

        public virtual student student { get; set; }
    }
}
