//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentsInCourse
    {
        public int index { get; set; }
        public Nullable<int> studentID { get; set; }
        public Nullable<int> courseID { get; set; }
    
        public virtual courses cours { get; set; }
        public virtual student student { get; set; }
    }
}
